name: Build
on:
  push:
    branches:
      - main
      - 'issue*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: get dependencies
        run: |
          - npm ci
      - name: lint with eslint
        run: |
          npm run lint
      - name: build
        run: |
          npm run build
      - name: unit tests with angular core testing
        run: |
          npm run test

